import { DataTable } from "@/components/data-table/data-table";
import type { UserAPISchema } from "@/types/user";
import { DashboardHeader } from "../../components/dashboard-header";
import { columns } from "./components/pending-registrations-table-columns";

export default function PendingRegistrationsPage() {
  return (
    <>
      <DashboardHeader />
      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
        <DataTable<UserAPISchema>
          columns={columns}
          data={[
            {
              id: 1,
              status: "approved",
              type: "mechanic",
              name: "João Silva",
              email: "joao.silva@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "12345678901",
              bases: [1],
              assistant: false,
              createdAt: new Date("2024-01-15"),
              updatedAt: new Date("2024-01-15"),
            },
            {
              id: 2,
              status: "reproved",
              type: "budgetist",
              name: "Maria Santos",
              email: "maria.santos@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "98765432101",
              bases: [2],
              assistant: false,
              createdAt: new Date("2024-01-16"),
              updatedAt: new Date("2024-01-16"),
            },
            {
              id: 3,
              status: "pending",
              type: "mechanic",
              name: "Pedro Oliveira",
              email: "pedro.oliveira@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "45678912301",
              bases: [3],
              assistant: true,
              createdAt: new Date("2024-01-17"),
              updatedAt: new Date("2024-02-01"),
            },
            {
              id: 4,
              status: "pending",
              type: "mechanic",
              name: "Ana Costa",
              email: "ana.costa@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "78912345601",
              bases: [4],
              assistant: false,
              createdAt: new Date("2024-01-18"),
              updatedAt: new Date("2024-01-18"),
            },
            {
              id: 5,
              status: "pending",
              type: "budgetist",
              name: "Lucas Pereira",
              email: "lucas.pereira@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "32165498701",
              bases: [5],
              assistant: false,
              createdAt: new Date("2024-01-19"),
              updatedAt: new Date("2024-01-19"),
            },
            {
              id: 6,
              status: "pending",
              type: "mechanic",
              name: "Fernanda Lima",
              email: "fernanda.lima@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "65498732101",
              bases: [6],
              assistant: true,
              createdAt: new Date("2024-01-20"),
              updatedAt: new Date("2024-02-05"),
            },
            {
              id: 7,
              status: "pending",
              type: "budgetist",
              name: "Ricardo Santos",
              email: "ricardo.santos@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "95175384201",
              bases: [7],
              assistant: false,
              createdAt: new Date("2024-01-21"),
              updatedAt: new Date("2024-01-21"),
            },
            {
              id: 8,
              status: "pending",
              type: "mechanic",
              name: "Juliana Alves",
              email: "juliana.alves@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "75395145601",
              bases: [8],
              assistant: false,
              createdAt: new Date("2024-01-22"),
              updatedAt: new Date("2024-01-22"),
            },
            {
              id: 9,
              status: "pending",
              type: "mechanic",
              name: "Marcos Silva",
              email: "marcos.silva@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "95175384201",
              bases: [9],
              assistant: true,
              createdAt: new Date("2024-01-23"),
              updatedAt: new Date("2024-02-10"),
            },
            {
              id: 10,
              status: "pending",
              type: "budgetist",
              name: "Carla Oliveira",
              email: "carla.oliveira@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "15935785201",
              bases: [10],
              assistant: false,
              createdAt: new Date("2024-01-24"),
              updatedAt: new Date("2024-01-24"),
            },
            {
              id: 11,
              status: "pending",
              type: "mechanic",
              name: "Roberto Costa",
              email: "roberto.costa@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "35795145601",
              bases: [11],
              assistant: false,
              createdAt: new Date("2024-01-25"),
              updatedAt: new Date("2024-01-25"),
            },
            {
              id: 12,
              status: "pending",
              type: "budgetist",
              name: "Patricia Lima",
              email: "patricia.lima@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "95175384201",
              bases: [12],
              assistant: false,
              createdAt: new Date("2024-01-26"),
              updatedAt: new Date("2024-01-26"),
            },
            {
              id: 13,
              status: "pending",
              type: "mechanic",
              name: "Felipe Santos",
              email: "felipe.santos@example.com",
              birthDate: new Date("1990-01-01"),
              cpf: "75395145601",
              bases: [13],
              assistant: true,
              createdAt: new Date("2024-01-27"),
              updatedAt: new Date("2024-02-15"),
            },
          ]}
          filterColumn="email"
          filterPlaceholder="Pesquisar por email"
        />
      </div>
    </>
  );
}
