import { DashboardHeader } from "../../components/dashboard-header";
import { DataTable } from "@/components/data-table/data-table";
import { columns } from "./components/users-table-columns";

export default function BusinessIntelligencePage() {
  return (
    <>
      <DashboardHeader />
      <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
        <DataTable columns={columns} data={[
          {
            id: 1,
            userType: "mechanic",
            name: "João Silva",
            email: "joao.silva@example.com",
            cpf: "12345678901",
            base: "Base São Paulo",
            firm: "Firma 1",
            assistant: false,
            createdAt: new Date("2024-01-15"),
            updatedAt: new Date("2024-01-15"),
          },
          {
            id: 2,
            userType: "budgetist",
            name: "Maria Santos",
            email: "maria.santos@example.com",
            cpf: "98765432101",
            base: "Base 2",
            firm: "Firma ABC",
            assistant: false,
            createdAt: new Date("2024-01-16"),
            updatedAt: new Date("2024-01-16"),
          },
          {
            id: 3,
            userType: "mechanic",
            name: "Pedro Oliveira",
            email: "pedro.oliveira@example.com",
            cpf: "45678912301",
            base: "Base Rio",
            firm: "Firma 3",
            assistant: true,
            createdAt: new Date("2024-01-17"),
            updatedAt: new Date("2024-02-01"),
          },
          {
            id: 4,
            userType: "mechanic",
            name: "Ana Costa",
            email: "ana.costa@example.com",
            cpf: "78912345601",
            base: "Base Curitiba",
            firm: "Firma 4",
            assistant: false,
            createdAt: new Date("2024-01-18"),
            updatedAt: new Date("2024-01-18"),
          },
          {
            id: 5,
            userType: "budgetist",
            name: "Lucas Pereira",
            email: "lucas.pereira@example.com",
            cpf: "32165498701",
            base: "Base 5",
            firm: "Firma XYZ",
            assistant: false,
            createdAt: new Date("2024-01-19"),
            updatedAt: new Date("2024-01-19"),
          },
          {
            id: 6,
            userType: "mechanic",
            name: "Fernanda Lima",
            email: "fernanda.lima@example.com",
            cpf: "65498732101",
            base: "Base Brasília",
            firm: "Firma 6",
            assistant: true,
            createdAt: new Date("2024-01-20"),
            updatedAt: new Date("2024-02-05"),
          },
          {
            id: 7,
            userType: "budgetist",
            name: "Ricardo Santos",
            email: "ricardo.santos@example.com",
            cpf: "95175384201",
            base: "Base 7",
            firm: "Firma 123",
            assistant: false,
            createdAt: new Date("2024-01-21"),
            updatedAt: new Date("2024-01-21"),
          },
          {
            id: 8,
            userType: "mechanic",
            name: "Juliana Alves",
            email: "juliana.alves@example.com",
            cpf: "75395145601",
            base: "Base Salvador",
            firm: "Firma 8",
            assistant: false,
            createdAt: new Date("2024-01-22"),
            updatedAt: new Date("2024-01-22"),
          },
          {
            id: 9,
            userType: "mechanic",
            name: "Marcos Silva",
            email: "marcos.silva@example.com",
            cpf: "95175384201",
            base: "Base Recife",
            firm: "Firma 9",
            assistant: true,
            createdAt: new Date("2024-01-23"),
            updatedAt: new Date("2024-02-10"),
          },
          {
            id: 10,
            userType: "budgetist",
            name: "Carla Oliveira",
            email: "carla.oliveira@example.com",
            cpf: "15935785201",
            base: "Base 10",
            firm: "Firma QWE",
            assistant: false,
            createdAt: new Date("2024-01-24"),
            updatedAt: new Date("2024-01-24"),
          },
          {
            id: 11,
            userType: "mechanic",
            name: "Roberto Costa",
            email: "roberto.costa@example.com",
            cpf: "35795145601",
            base: "Base Fortaleza",
            firm: "Firma 11",
            assistant: false,
            createdAt: new Date("2024-01-25"),
            updatedAt: new Date("2024-01-25"),
          },
          {
            id: 12,
            userType: "budgetist",
            name: "Patricia Lima",
            email: "patricia.lima@example.com",
            cpf: "95175384201",
            base: "Base 12",
            firm: "Firma RTY",
            assistant: false,
            createdAt: new Date("2024-01-26"),
            updatedAt: new Date("2024-01-26"),
          },
          {
            id: 13,
            userType: "mechanic",
            name: "Felipe Santos",
            email: "felipe.santos@example.com",
            cpf: "75395145601",
            base: "Base Manaus",
            firm: "Firma 13",
            assistant: true,
            createdAt: new Date("2024-01-27"),
            updatedAt: new Date("2024-02-15"),
          },
          {
            id: 14,
            userType: "mechanic",
            name: "Amanda Pereira",
            email: "amanda.pereira@example.com",
            cpf: "95175384201",
            base: "Base Belém",
            firm: "Firma 14",
            assistant: false,
            createdAt: new Date("2024-01-28"),
            updatedAt: new Date("2024-01-28"),
          },
          {
            id: 15,
            userType: "budgetist",
            name: "Bruno Alves",
            email: "bruno.alves@example.com",
            cpf: "15935785201",
            base: "Base 15",
            firm: "Firma UIO",
            assistant: false,
            createdAt: new Date("2024-01-29"),
            updatedAt: new Date("2024-01-29"),
          },
          {
            id: 16,
            userType: "mechanic",
            name: "Camila Silva",
            email: "camila.silva@example.com",
            cpf: "35795145601",
            base: "Base Porto Alegre",
            firm: "Firma 16",
            assistant: true,
            createdAt: new Date("2024-01-30"),
            updatedAt: new Date("2024-02-20"),
          },
          {
            id: 17,
            userType: "budgetist",
            name: "Diego Oliveira",
            email: "diego.oliveira@example.com",
            cpf: "95175384201",
            base: "Base 17",
            firm: "Firma PAS",
            assistant: false,
            createdAt: new Date("2024-01-31"),
            updatedAt: new Date("2024-01-31"),
          },
          {
            id: 18,
            userType: "mechanic",
            name: "Eduarda Costa",
            email: "eduarda.costa@example.com",
            cpf: "75395145601",
            base: "Base Florianópolis",
            firm: "Firma 18",
            assistant: false,
            createdAt: new Date("2024-02-01"),
            updatedAt: new Date("2024-02-01"),
          },
          {
            id: 19,
            userType: "mechanic",
            name: "Fábio Lima",
            email: "fabio.lima@example.com",
            cpf: "95175384201",
            base: "Base Vitória",
            firm: "Firma 19",
            assistant: true,
            createdAt: new Date("2024-02-02"),
            updatedAt: new Date("2024-02-25"),
          },
          {
            id: 20,
            userType: "budgetist",
            name: "Gabriela Santos",
            email: "gabriela.santos@example.com",
            cpf: "15935785201",
            base: "Base 20",
            firm: "Firma LKJ",
            assistant: false,
            createdAt: new Date("2024-02-03"),
            updatedAt: new Date("2024-02-03"),
          }
        ]} filterColumn="name" filterPlaceholder="Pesquisar por nome" />
      </div>
    </>
  );
}
